/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: 1,
      username: "Deneme1",
      password: "123456",
      email: "Deneme1@mail.com",
      firstName: "Yusuf",
      lastName: "Çolak",
      gender: "Erkek",
      birthday: "01.01.2023",
    },
    {
      id: 2,
      username: "Deneme2",
      password: "123456",
      email: "Deneme2@mail.com",
      firstName: "Ahmet",
      lastName: "Çoban",
      gender: "Erkek",
      birthday: "01.01.2023",
    },
  ]);
  await knex("seferler").del();
  await knex("seferler").insert([
    {
      id: 1,
      seferSirketResim:
        "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3195-sm.png",
      seferSirketi: "KamilKoç",
      seferTarihi: "26/7/2023",
      seferSuresi: "5 Saat ",
      seferSaati: "07:00",
      seferUcreti: "500",
      seferKapasitesi: "50",
      seferKoltukDüzeni: "2+2",
      seferKalkisYeri: "İstanbul",
      seferVarisYeri: "Ankara",
      seferAciklama: "İstanbul Ankara arası seferlerimiz başlamıştır...",
    },
    {
      id: 2,
      seferSirketResim:
        "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3421-sm.png",
      seferSirketi: "Pamukkale",
      seferTarihi: "26/7/2023",
      seferSuresi: "6 Saat",
      seferSaati: "08:00",
      seferUcreti: "400",
      seferKapasitesi: "50",
      seferKoltukDüzeni: "2+2",
      seferKalkisYeri: "Ankara",
      seferVarisYeri: "İstanbul",
      seferAciklama: "Ankara İstanbul arası seferlerimiz başlamıştır..",
    },
    {
      id: 3,
      seferSirketResim:
        "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3195-sm.png",
      seferSirketi: "KamilKoç",
      seferTarihi: "26/7/2023",
      seferSuresi: "3 Saat",
      seferSaati: "09:00",
      seferUcreti: "250",
      seferKapasitesi: "50",
      seferKoltukDüzeni: "2+2",
      seferKalkisYeri: "Ankara",
      seferVarisYeri: "İstanbul",
      seferAciklama: "Ankara İstanbul arası seferlerimiz başlamıştır..",
    },
    {
      id: 4,
      seferSirketResim:
        "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3421-sm.png",
      seferSirketi: "Pamukkale",
      seferTarihi: "26/7/2023",
      seferSuresi: "4 Saat",
      seferSaati: "12:00",
      seferUcreti: "275",
      seferKapasitesi: "50",
      seferKoltukDüzeni: "2+2",
      seferKalkisYeri: "İstanbul",
      seferVarisYeri: "Ankara",
      seferAciklama: "İstanbul Ankara arası seferlerimiz başlamıştır..",
    },
    {
      id: 5,
      seferSirketResim:
        "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3195-sm.png",
      seferSirketi: "KamilKoç",
      seferTarihi: "26/7/2023",
      seferSuresi: "3 Saat",
      seferSaati: "14:00",
      seferUcreti: "450",
      seferKapasitesi: "50",
      seferKoltukDüzeni: "2+2",
      seferKalkisYeri: "Ankara",
      seferVarisYeri: "İstanbul",
      seferAciklama: "Ankara İstanbul arası seferlerimiz başlamıştır..",
    },
    {
      id: 6,
      seferSirketResim:
        "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3195-sm.png",
      seferSirketi: "KamilKoç",
      seferTarihi: "26/7/2023",
      seferSuresi: "7 Saat",
      seferSaati: "16:00",
      seferUcreti: "375",
      seferKapasitesi: "50",
      seferKoltukDüzeni: "2+2",
      seferKalkisYeri: "İstanbul",
      seferVarisYeri: "Ankara",
      seferAciklama: "İstanbul Ankara arası seferlerimiz başlamıştır..",
    },
  ]);

  await knex("koltuklar").del();
  await knex("koltuklar").insert([
    {
      seferId: 1,
      koltukNo: 6,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 12,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 3,
      UserId: 3,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 14,
      UserId: 1,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 25,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 46,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 37,
      UserId: 1,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 28,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 19,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 1,
      koltukNo: 11,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },

    // Sefer 2 için koltuklar
    {
      seferId: 2,
      koltukNo: 2,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 22,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 13,
      UserId: 3,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 4,
      UserId: 1,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 15,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 36,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 27,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 48,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 19,
      UserId: 3,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 2,
      koltukNo: 10,
      UserId: 1,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },

    // Sefer 3 için koltuklar
    {
      seferId: 4,
      koltukNo: 11,
      UserId: 1,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 42,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 13,
      UserId: 3,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 24,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 15,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 46,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 37,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 28,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 9,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 4,
      koltukNo: 6,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },

    {
      seferId: 5,
      koltukNo: 4,
      UserId: 1,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 32,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 23,
      UserId: 3,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 14,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 25,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 16,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 47,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 28,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 39,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 5,
      koltukNo: 49,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },

    {
      seferId: 6,
      koltukNo: 1,
      UserId: 1,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 42,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 33,
      UserId: 3,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 14,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 25,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 16,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 27,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 38,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 39,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 48,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 4,
      UserId: 1,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 15,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 17,
      UserId: 3,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 19,
      UserId: 2,
      cinsiyet: "Kadın",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 20,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 22,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 27,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 35,
      UserId: 2,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 42,
      UserId: 1,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
    {
      seferId: 6,
      koltukNo: 45,
      UserId: 3,
      cinsiyet: "Erkek",
      koltukFiyati: 500,
    },
  ]);
};
